[package]
name = "rssite"
version = "0.1.4"
edition = "2024"
authors = ["Mark Veltzer <mark.veltzer@gmail.com>"]
description = "Static site generator with a pre-declared output manifest"
license = "MIT"
repository = "https://github.com/veltzer/rssite"

[profile.release]
strip = true
lto = true
codegen-units = 1
